version: '3'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/thingsflow
    env_file:
      - ./.env
    networks:
      - local

networks:
  local:
    driver: bridge
